version: '3'
services:

    mongodb:
      image: mongo:4.0.0
      volumes:
        - wktmulti-mongodb-data:/data/db
      ports:
        - 20007:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: Lideo123^
      command: mongod

networks:
  default:

volumes:
  wktmulti-mongodb-data:


