mongodb:
  max:
    pool:
      size: 300

spring:
  application:
    name: wktmulti
  data:
    mongodb:
      database:  wktmulti
      port: 27017
      authentication-database: admin
      host: localhost:20007
      password: Lideo123^
      username: root

server:
  port : 8080

